[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Bagh"
authors = [{name = "Achintya Kumar Dutta", email = "achintya@chem.iitb.ac.in"}]
dynamic = ["version", "description"]
